### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [amzn/amazon-pay-api-sdk-dotnet#2]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/csharp/
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by lemked** [comment]
Dear @Neustradamus ,

We have encountered some issues with the latest BouncyCastle version (1.8.6), which is why we haven't updated our dependencies yet. I'll provide an update here once that the issues has been sorted out.

Kind regards,
Daniel

**Comment by Neustradamus** [comment]
@lemked: Thanks for your reply!

**Comment by larrybud2004** [comment]
I take it this is never going to be updated?

**Comment by Neustradamus** [comment]
@larrybud2004: Thanks to join me in this security problem.

**Comment by bjguillot** [comment]
We have a related open issue with bc-csharp project: https://github.com/bcgit/bc-csharp/issues/252 and have not had a response yet.  We can try one of the newer BC builds and see if the RSA PSS signing bug may have been fixed with the library in the meantime, but if it is still broken, we will be unable to upgrade until the issue introduced in BC 1.8.6.1 has been fixed.

**Comment by lemked** [comment]
Version 2.4.4 of our SDK bumps the version number of Bouncy Castle to version 1.8.9:
https://github.com/amzn/amazon-pay-api-sdk-dotnet/releases/tag/2.4.4

Closing issue.

**Comment by Neustradamus** [comment]
@lemked: Good job, thanks!

At the same time, can you update to 1.8.10?
